---
kind: common.Repository
spec:
  licenses:
    - id: BSL-1.1
      params:
        Licensor: Sidero Labs, Inc.
        LicensedWork: Omni
        Copyright: (c) 2026 Sidero Labs, Inc.
        ChangeDate: "2030-04-30"
        ChangeLicense: Mozilla Public License, version 2.0
        EnterpriseLink: https://www.siderolabs.com/contact/
        AdditionalUseGrant: You may make non-production use of the Licensed Work, including for testing and evaluation, or for personal use in a home lab environment. Any use of the Licensed Work in a production environment requires a commercial license from Sidero Labs.
      header: |
        // Copyright (c) 2026 Sidero Labs, Inc.
        //
        // Use of this software is governed by the Business Source License
        // included in the LICENSE file.
  licenseChecks:
    - root: "."
      header: |
        // Copyright (c) 2026 Sidero Labs, Inc.
        //
        // Use of this software is governed by the Business Source License
        // included in the LICENSE file.
      includeSuffixes:
        - .go
      excludeSuffixes:
        - .pb.go
        - .generated.go
      skipPaths:
        - .git
        - testdata/
